# JThermodynamics Species List
# List of species to process when running the main program

# Temperature range for calculations (K)
temperature_range: [100, 10000]
temperature_step: 10  # Step size for temperature points

# Species list
species:
  - N2
  - O2
  - H2
  - H2O
  - CO2
  - CO
  - NO
  - NO2
  - N2O
  - O3
  - OH
  - HO2
  - H
  - O
  - N
  - NH3
  - NH2
  - NH
  - HNO3
  - HONO
  - HNO
  - H2O2
  - CH4
  - CH2
  - CH
  - CH3
  - CH2O
  - CHO
  - CHOOH
  - HCN
  - N2H4
  - NCO
  - NCN
  - HCNO
  - CN
  - CN-
  - NO+
  - NO-
  - NO2+
  - NO2-
  - NO3-
  - O-
  - O2-
  - O2+
  - O+
  - O3+
  - N2+
  - N+
  - N-
  - N2-
  - H+
  - H-
  - H2+
  - H2O+
  - H2O-
  - H3O+
  - HO2-
  - OH+
  - OH-
  - CO+
  - CO2+
  - CO-
  - CO2-
  - CH+
  - CHO+
  - C+
  - C-
  - N2O+
  - HNO2+
  - HNO3+
  - HNO+
  - SO
  - SO2
  - SO3
  - S
  - Ar
  - He
  - He+
  - Ne
  - Xe
  - Xe+
  - e-

# Output options
output:
  save_to_database: true
  generate_plots: true
  plot_format: "png"
  plot_directory: "plots"
  log_level: "info"
  use_log_temperature: true  # Use logarithmic temperature scale